### ISSUE TITLE
README.md: Found a way to run this in google colab

### ISSUE THREAD

**Issue by metapea** [qaixerabbas/youtube-frame-capture#2]
1. Upload or drag and drop cli.py and  youtube_videos_capture_frames.py to the current directory. The default is /content/
2.  Run `pip install opencv_python vidgear yt-dlp`
3. Make a new folder for output
4. Run `!python cli.py --videolink "(youtube link)" --destination "/(content or the current directory)/(folder name)/"`

To zip, Just run `!zip -r /(content or current directory)/(file name).zip /content/(folder name)`
Just add this to README.md

**Comment by qaixerabbas** [comment]
Hey @metapea thank you for contributing. Can you provide a link to your Colab here? It might be helpful for others to run code directly in Colab without setting any additional environment.

**Comment by metapea** [comment]
Here's the .ipynb you can import:
[ytfe.zip](https://github.com/qaixerabbas/youtube-frame-capture/files/11857762/ytfe.zip) (can't upload .ipynb here, so here a .zip with the file)
it's also have `!rm -rf /(content or current directory)/(folder)` to clean folders. 
Just run it in default google colab. No "additional environment" is needed, but just uploading cli.py and youtube_videos_capture_frames.py or running pip install if that counts
