### ISSUE TITLE
Feature requests: Implement "prune by similarity"

### ISSUE THREAD

**Issue by metapea** [qaixerabbas/youtube-frame-capture#3]
I found a similar tool called [FramesExtractor_GUI](https://civitai.com/models/85850/frames-extractor-and-similarity-prune-utility-tool) (Frames Extractor & similarity prune - Utility Tool), and the program can prune the frames for similarity by a similarity score, it takes awhile depending the similarity score & frames but it would be a nice thing to add as a argument.

**Comment by qaixerabbas** [comment]
Hey @metapea, Thank for your suggestions.

I have already planned to do something similar by providing an extra argument in cli to tackle the similar images. I will try to add this once I get free from current commitments. Meanwhile you can check https://github.com/qaixerabbas/deepds where I plan to add this feature and many more.
